name: "Build pxt-letssteam on pull request"

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    container:
      image: nedseb/arm-gcc-none-eabi:latest
      options: --user 1001 --security-opt no-new-privileges
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g pxt
          npm install
      - name: pxt ci
        run: |
          pxt ci
        env:
          PXT_FORCE_LOCAL: 1 
          PXT_NODOCKER : 1
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true
