name: "Build pxt-letssteam target"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    container:
      image: letssteam/makecode-toolchain:latest
      options: --user 1001 --security-opt no-new-privileges
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g pxt
          npm install
      - name: pxt ci
        run: |
          pxt ci
        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
          PXT_FORCE_LOCAL: 1
          PXT_NODOCKER: 1
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          PXT_RELEASE_REPO: ${{ secrets.PXT_RELEASE_REPO }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true
