name: "Download and build approved github packages"

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        branch: [main]
    container:
      image: nedseb/arm-gcc-none-eabi:latest
      options: --user 1001 --security-opt no-new-privileges
    env:
      PXT_FORCE_LOCAL: 1 
      PXT_NODOCKER : 1
      PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
      PXT_RELEASE_REPO: ${{ secrets.PXT_RELEASE_REPO }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo npm install -g pxt
          npm install
      - name: pxt buildtarget
        run: pxt buildtarget
      - name: cache build output
        uses: actions/cache@v1
        env:
          cache-name: cache-testghpkgs
        with:
          path: temp/ghpkgs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-       
      - name: pxt testghpkgs
        run: pxt testghpkgs
        env:
          PXT_FORCE_GITHUB_PROXY: 1
      - name: upload build log
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs-${{ matrix.branch }}
          path: temp/ghpkgs/*.txt
