name: "Publish static package to pxt-lets-steam-static and deploy makecode.lets-steam.eu"

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    container:
      image: letssteam/makecode-toolchain:latest
      options: --user 1001 --security-opt no-new-privileges
    env:
      PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
      PXT_RELEASE_REPO: ${{ secrets.PXT_RELEASE_REPO }}
      PXT_NODOCKER: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - run: npm run staticpackage

      - name: Pushes to pxt-lets-steam-static repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "built/packaged"
          destination-github-username: "letssteam"
          destination-repository-name: "pxt-lets-steam-static"
          user-email: sebastien@nedjar.com
          user-name: nedseb
          target-branch: main

  synchronize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
        with:
          repository: "microsoft/pxt-stm32-iot-node"
          ref: master
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Synchronize editors
        run: |
          git config user.name nedseb
          git config user.email sebastien@nedjar.com
          git remote add letssteam https://github.com/letssteam/pxt-lets-steam
          git fetch letssteam --no-tags
          git merge letssteam/main -m "merge with pxt-lets-steam:$SOURCE_TAG" -s ours --allow-unrelated-histories
          git push origin master
          git tag -a $SOURCE_TAG -m "$SOURCE_TAG"
          git push origin $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to digital ocean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APPLICATION_ID_PROD}} --force-rebuild
