name: "Publish static package to pxt-lets-steam-static"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        branch: [main]
    container:
      image: letssteam/makecode-toolchain:latest
      options: --user 1001 --security-opt no-new-privileges
    env:
      PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
      PXT_RELEASE_REPO: ${{ secrets.PXT_RELEASE_REPO }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install -g pxt
          npm install
      - name: build static package
        run: yarn run staticpackage
      - name: cache build output
        uses: actions/cache@v1
        env:
          cache-name: cache-testghpkgs
        with:
          path: built/packaged
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Pushes to pxt-lets-steam-static repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "built/packaged"
          destination-github-username: "letssteam"
          destination-repository-name: "pxt-lets-steam-static"
          user-email: sebastien@nedjar.com
          user-name: nedseb
          target-branch: main
